#
# Sockeye release 0.2
#
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prime
  labels:
    eventing.knative.dev/autotrigger: "true"
  annotations:
    trigger.eventing.knative.dev/filter: |
      [{"type":"io.ducktagon.number.prime"}]
spec:
  template:
    spec:
      containers:
        - image: docker.io/n3wscott/sockeye-e92784dbbc40447852d8e5fa42eed6b4@sha256:8de604543325f25aa08267928a093d127c5d7d7aad3019d371deb42123ca6dd8


