#
# Sockeye release 0.2
#
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: odd
spec:
  template:
    spec:
      containers:
        - image: docker.io/n3wscott/sockeye-e92784dbbc40447852d8e5fa42eed6b4@sha256:8de604543325f25aa08267928a093d127c5d7d7aad3019d371deb42123ca6dd8

---

#
# * trigger
#
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: odd-sockeye
spec:
  filter:
    attributes:
      type: io.ducktagon.number.odd
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: odd

---


